### ISSUE TITLE
Luno.com is a SCAM!

### ISSUE THREAD

**Issue by nextime** [luno/luno-php#31]
Don't use it, they STOLE your money and don't let you withdraw with escuses after escuses, when they answer at all.

**Comment by carelvwyk** [comment]
So you contact a fake profile of the CEO on Facebook to try and resolve your problem... In reality, you probably triggered flag on your friend's account, probably because multiple people were trying to log in / link devices? Opening issues on opensource github libraries to air your grievances reflects very badly on you.

![image](https://user-images.githubusercontent.com/2698547/146665597-33f1c8e7-ffbd-422d-b783-7d6b561b9380.png)
